### ISSUE TITLE
npm start fails

### ISSUE THREAD

**Issue by dobe0002** [blackjk3/react-form-builder#1]
I wanted to take a look at the react-form-builder but I receive errors when I run npm start.  Here is the contents of the npm-debug.log file:

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@2.10.1
3 info using node@v0.12.4
4 verbose node symlink /usr/local/bin/node
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart react-forms-builder@0.0.1
7 info start react-forms-builder@0.0.1
8 verbose unsafe-perm in lifecycle true
9 info react-forms-builder@0.0.1 Failed to exec start script
10 verbose stack Error: react-forms-builder@0.0.1 start: `webpack-dev-server --hot --inline`
10 verbose stack spawn ENOENT
10 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:17:16)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid react-forms-builder@0.0.1
12 verbose cwd /Users/dobe0002/Desktop/Projects/GIT/react-form-builder
13 error Darwin 14.4.0
14 error argv "node" "/usr/local/bin/npm" "start"
15 error node v0.12.4
16 error npm  v2.10.1
17 error file sh
18 error code ELIFECYCLE
19 error errno ENOENT
20 error syscall spawn
21 error react-forms-builder@0.0.1 start: `webpack-dev-server --hot --inline`
21 error spawn ENOENT
22 error Failed at the react-forms-builder@0.0.1 start script 'webpack-dev-server --hot --inline'.
22 error This is most likely a problem with the react-forms-builder package,
22 error not with npm itself.
22 error Tell the author that this fails on your system:
22 error     webpack-dev-server --hot --inline
22 error You can get their info via:
22 error     npm owner ls react-forms-builder
22 error There is likely additional logging output above.
23 verbose exit [ 1, true ]

**Comment by blackjk3** [comment]
Thanks for submitting an issue.  One quick question.  Did you run npm install first within the project?  Sorry, I don't think that step was in the readme
```bash
$ npm install
```

**Comment by blackjk3** [comment]
@dobe0002 Any luck? I would like to close the issue if the above worked for you.

**Comment by dobe0002** [comment]
Yes - that worked!  I guess that was kind of newbie mistake on my part ;-)

Thank you for your assistance.

Kim

-----------------------------

Kim Doberstein

Portal Developer
Office of Informational Technology (OIT)
University of Minnesotadobe0002@umn.edu

Rah Rah Rah - Ski-U-Mah

**Comment by blackjk3** [comment]
Awesome! Good luck, and feel free to reach out with further questions.
