### ISSUE TITLE
The folder 'vendor' is missing

### ISSUE THREAD

**Issue by jhetchan** [blackjk3/react-form-builder#13]
ERROR in ENOENT: no such file or directory, scandir '/Users/Jhet/react/form-builder/react-form-builder/node_modules/node-sass/vendor'
 @ ./css/application.css.scss 4:14-126 13:2-17:4 14:20-132

webpack: bundle is now VALID.

**Comment by blackjk3** [comment]
@jhetchan did you try doing something like this?

https://github.com/sass/node-sass/issues/1579#issuecomment-227663782

**Comment by mbluemer** [comment]
Can confirm running `npm rebuild node-sass` fixes the issue.
